USER $uid

# Install phoenix
RUN mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez

COPY /scripts/docker-bootstrap.sh /docker-bootstrap.sh
CMD /docker-bootstrap.sh
