version: "3"
services:
  postgresdb:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      webnet:
        aliases:
          - postgresdb

  webapp:
    tty: true
    build:
      context: ../..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../..:/opt/app
    environment:
      - PORT=4000
      - PG_HOST=postgresdb
      - MIX_ENV=dev
    links:
      - postgresdb
    ports:
      - "4000:4000"
    networks:
      - webnet

networks:
  webnet:
